apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangar-app-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hangar-aeronave
      version: candidate
  template:
    metadata:
      labels:
        app: hangar-aeronave
        version: candidate
    spec:
      containers:
      - name: web-app
        image: dockeruser/hangar-app:2.1.0
        ports:
        - containerPort: 5000
